name: knitting
description: "A new Flutter project."
publish_to: 'none'

version: 0.3.2+7

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.4
  image: ^4.5.3
  firebase_core: ^3.12.0
  protobuf: ^3.1.0
  grpc: ^4.0.1
  firebase_auth: ^5.5.1
  go_router: ^14.8.1
  gap: ^3.0.1
  image_picker: ^1.1.2
  fixnum: ^1.1.1
  image_picker_web: ^4.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^2.8.1

flutter_icons:
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

    - family: ZenMaruGothic
      fonts:
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Black.ttf
          weight: 900
