name: Flutter_Analyzer

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - release

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: flutter_client
    steps:
      - uses: actions/checkout@v4
      - name: Read Flutter version from .fvmrc
        id: flutter_version
        run: echo "FLUTTER_VERSION=$(awk -F'\"' '/flutter/ {print $4}' ./.fvmrc)" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter analyze
